main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path("", views.homepage,name="homepage"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    path("pub_entry/", views.pub_entry, name="pub_entry"),
    path("add_entry/", views.add_entry, name="add_entry"),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
    path("thisweek/", views.thisweek, name="thisweek"),
    path("allentry/", views.allentry, name="allentry"),
    path("Search/", views.Search, name="Search"),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('tinymce/', include('tinymce.urls'))
]

main/models.py
from django.db import models
from datetime import datetime
from django.conf import settings
from django.utils import timezone



class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    writer = models.CharField(max_length=200, default='')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    public_or_private = models.CharField(max_length=200)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title
class search(models.Model):
    author = models.CharField(max_length=200)
    title = models.CharField(max_length=200)


    def __str__(self):
        return self.title

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post, search



class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class PostForm(forms.ModelForm):
  

    class Meta:
        model = Post
        fields = ('writer', 'title', 'text','public_or_private')

class SearchForm(forms.ModelForm):
  

    class Meta:
        model = search
        fields = ('author', 'title')
        

main/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import  AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.urls import reverse
from .forms import NewUserForm
from .forms import PostForm, SearchForm
from .models import Post, search
from django.utils import timezone
from datetime import date, timedelta
from django.db.models import Q

# Create your views here.
def homepage(request):
	return render(request=request,
		          template_name="main/home.html")
def register(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f"New account created: {username}")
			return redirect("main:register")
		else:
			for msg in form.error_messages:
				messages.error(request,f"{msg}:{form.error_messages[msg]}")
	form = NewUserForm
	return render(request,"main/register.html", context={"form":form})
def logout_request(request):
	logout(request)
	messages.info(request, "Logged out succesfully!")
	return redirect("main:login")
def login_request(request):
	if request.method == 'POST':
		form = AuthenticationForm(request=request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}")
				return HttpResponseRedirect(reverse("main:thisweek"))
				
				
			else:
				messages.error(request, "Invalid username or password.")
		else:
			messages.error(request, "Invalid username or password.")

	form = AuthenticationForm()
	return render(request,
		          "main/login.html",
				  context={"form":form})
def pub_entry(request):
	posts = Post.objects.filter(public_or_private="public").order_by('published_date')
	return render(request=request, template_name="main/pub_entry.html", context={'posts': posts})
def add_entry(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect("main:thisweek")
    else:
        form = PostForm()
    return render(request=request, template_name="main/add_entry.html", context={'form': form})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'main/post_detail.html', {'post': post})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('main:allentry')
    else:
        form = PostForm(instance=post)
    return render(request=request, template_name="main/add_entry.html", context={'form': form})
def thisweek(request):
	user = request.user
	d=date.today()-timedelta(days=7)
	posts = Post.objects.filter(author = request.user, published_date__gte=d, published_date__lte=timezone.now()).order_by('published_date')
	return render(request=request, template_name="main/thisweek.html", context={'posts': posts, 'user':user})
def allentry(request):
	user = request.user
	posts = Post.objects.filter(author = request.user).order_by('published_date')
	return render(request=request, template_name="main/allentry.html", context={'posts': posts, 'user':user})
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('main:allentry')
def Search(request):
	if request.method == "GET":
		form = SearchForm(request.GET)
		if form.is_valid():
			auth=form.cleaned_data['author']
			tit=form.cleaned_data['title']
			posts = Post.objects.filter(writer=auth, title=tit, public_or_private="public")
			return render(request=request, template_name="main/results.html", context={'posts': posts})
	else:
		form = SearchForm()
	return render(request=request, template_name="main/Search.html", context={'form': form})

main/templates/main/Search.html
{% extends "main/userpage.html" %}
{% block content %}
    <h2>New post</h2>
    <form method="GET" action="{% url 'main:Search' %}" class="post-form">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" class="save btn btn-default">Search</button>
    </form>
  {% endblock %}

main/templates/main/add_entry.html
{% extends "main/userpage.html" %}
{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" class="save btn btn-default">Save</button>
    </form>
  {% endblock %}

main/templates/main/allentry.html
{% extends "main/userpage.html" %}

{% block content %}
  <h1>hi {{user.username}} </h1>
   <div class="row">
    {% for post in posts %}
     <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
      <div class="card-header">published: {{ post.published_date }}</div>
      <div class="card-body">
        <h5 class="card-title"><a href="{% url 'main:post_detail' pk=post.pk %}">{{ post.title }}</a></h5>
        <p class="card-text">{{ post.text|linebreaksbr }}.</p>
      </div>
     </div>
    {% empty %}
      <li> No posts here....</li>
    {% endfor %}
   </div>
   
{% endblock %}

main/templates/main/header.html
<head>
  {% load static %}
 
  <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet" >
  <!-- Compiled and minified CSS -->
  <link href="{% static 'main/css/materialize.css' %}" rel="stylesheet" >
 
 
  <!-- Compiled and minified JavaScript 1920 1080 -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
  <link href="https://fonts.googleapis.com/css?family=Oswald:400,700|Roboto&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'main/fonts/icomoon/style.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/bootstrap-datepicker.css' %}">
  <link rel="stylesheet" href="{% static 'main/fonts/flaticon/font/flaticon.css' %}">

  <link rel="stylesheet" href="{% static 'main/css/aos.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/jquery.fancybox.min.css' %}">


  <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
  <style>
    body{
      background-image: url('{% static "main/images/wall1.jfif" %}');
      background-size:1300px 1080px;
      background-repeat: no-repeat;
 
    }
  </style>
 </head>

 <body>
 
 
  {% include "main/includes/navbar2.html" %}
  {% include "main/includes/messages.html" %}
  <div class="container">
   <br><br>
   {% block content %}
   {% endblock %}
  </div>
 
 </body>
 
 <script src="{% static 'tinymce/js/prism.js' %}" ></script>
 

main/templates/main/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>DIARYGENIE</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <link href="https://fonts.googleapis.com/css?family=Oswald:400,700|Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main/fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'main/fonts/flaticon/font/flaticon.css' %}">

    <link rel="stylesheet" href="{% static 'main/css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/jquery.fancybox.min.css' %}">


    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
  </head>
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300" style="background-image: url('{% static "main/images/desk2.jpg" %}');">

  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->


    <div class="site-navbar-wrap">

      <div class="site-navbar site-navbar-target js-sticky-header">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-6 col-lg-3">
              <h1 class="my-0 site-logo"><a href="{% url 'main:homepage' %}">DIARYGENIE</a></h1>
            </div>
            <div class="col-6 col-lg-9">
              <nav class="site-navigation text-right" role="navigation">
                <div class="container">

                  <div class="d-inline-block d-lg-none ml-md-0 mr-auto py-3 "><a href="#" class="site-menu-toggle js-menu-toggle text-black">
                    <span class="icon-menu h3"></span>
                  </a></div>

                  <ul class="site-menu main-menu js-clone-nav d-none d-lg-block">
                    <li><a href="#home-section" class="nav-link">Home</a></li>
                    <li><a href="#features-section" class="nav-link">Features</a></li>
                    <li><a href="#contact-section" class="nav-link">Contact</a></li>
                  </ul>
                </div>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div> <!-- END .site-navbar-wrap -->



    <div class="site-section" id="home-section">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mb-5">
            <h1 class="text-white serif text-uppercase mb-4">AN ONLINE DIARY SYSTEM</h1>
            <p class="text-white mb-5">This is a online diary system which helps you to keep your memories in a wonderful and safe world.</p>
            <!--<p><a href="#" class="btn btn-white px-4 py-3">LOG IN</a></p>-->
       <div class="row mt-5">
      <div class="col-md-6 m-auto">
        <div class="card card-body text-center text-white bg-info">
          <h2><i class="fas fa-address-book fa-3x"></i></h2>
          <p>Create an account or login here</p>
          <a href="register" class="btn btn-primary btn-block mb-2">Register</a>
          <a href="login" class="btn btn-secondary btn-block">Login</a>
        </div>
      </div>
    </div>
          </div>
        </div>
      <!-- <div class="row justify-content-center">
          <div class="col-md-10">
            <img src="/images/lamp3.jpg" alt="Image" class="img-fluid">
          </div>
        </div>-->
      </div>
    </div>

    <div class="site-section bg-light" id="features-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-7">
            <h2 class="heading">Features</h2>
            <p>The main features of this online diary system are following</p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="service h-100">
              <span class="wrap-icon">
                <span class="icon-book"></span>
              </span>
              <h3>Account</h3>
              <p>create your own account to enter to DIARYGENIE </p>
            </div>

          </div>
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="service h-100">
              <span class="wrap-icon">
                <span class="icon-bookmark"></span>
              </span>
              <h3>Create Posts</h3>
              <p>Create your own posts with memories</p>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="service h-100">
              <span class="wrap-icon">
                <span class="icon-files-o"></span>
              </span>
              <h3>Safe and Secure</h3>
              <p>We provide safe and secure platform to ensure the safety of your account and posts.</p>
            </div>
          </div>

          <div class="col-md-6 col-lg-4 mb-4">
            <div class="service h-100">
              <span class="wrap-icon">
                <span class="icon-font"></span>
              </span>
              <h3>Search</h3>
              <p>search feature for finding your memories faster</p>
            </div>

          </div>
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="service h-100">
              <span class="wrap-icon">
                <span class="icon-photo"></span>
              </span>
              <h3>Public-Private Posts</h3>
              <p>You can set your posts as public or private as your wish. You can see all public posts</p>
            </div>
          </div>

        </div>
      </div>
    </div>

    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 mb-5 mb-lg-0">
            <div class="row mb-5">
              <div class="col-12">
                <h3 class="footer-heading mb-4">About Us</h3>
                <p>This is a smart diary created using django!!!</p>
              </div>
            </div>
          </div>
          <div class="col-lg-3 ml-auto">

            

          </div>


          <div class="col-lg-4 mb-5 mb-lg-0" id="contact-section">
            <h1 class="footer-heading mb-4">Contact Us</h1>

            <div class="mb-5">
              <p>Have queries?mail us on diarygenie123@gmail.com</p>

            </div>




          </div>

        </div>
         <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <p>
          
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved 
      
            </p>
          </div>

        </div>
      </div>
    </footer>
  </div>

  <script src="{% static 'main/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'main/js/popper.min.js' %}"></script>
  <script src="{% static 'main/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'main/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'main/js/aos.js' %}"></script>
  <script src="{% static 'main/js/jquery.sticky.js' %}"></script>
  <script src="{% static 'main/js/stickyfill.min.js' %}"></script>
  <script src="{% static 'main/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'main/js/isotope.pkgd.min.js' %}"></script>

  <script src="{% static 'main/js/jquery.fancybox.min.js' %}"></script>
  <script src="{% static 'main/js/main.js' %}"></script>


  </body>
</html>

main/templates/main/includes/messages.html
{% if messages %}
       {% for message in messages %}
           {% if message.tags == 'success'%}
               <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
           {% elif message.tags == 'info'%}
               <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
           {% elif message.tags == 'warning'%}
               <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:10000});</script>
           {% elif message.tags == 'error'%}
               <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000});</script>
           {% endif %}
       {% endfor %}
{% endif %}

main/templates/main/includes/navbar.html
<nav class="navbar navbar-expand-xl navbar-black" style="background-color: black; width: 1240px;">
  <a class="navbar-brand" href="#" style="font-size: 30px;">DIARYGENIE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse container container-fluid" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a href="{% url 'main:thisweek' %}">Entries this week<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a href="{% url 'main:allentry' %}">All entries</a>
      </li>
      <li class="nav-item">
        <a  href="{% url 'main:add_entry' %}">Add entry</a>
      </li>

      <li class="nav-item dropdown">
        <a class="dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          More
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="background-color:black;">
            <a class="nav-link bg-black" href="{% url 'main:Search' %}" style="font-size: 13.5px;">Search public diary</a>
            <a class="nav-link bg-black" href="{% url 'main:pub_entry' %}" style="font-size: 13.5px;">Public posts by Users</a>
        </div>
      </li>
    </ul>
    <ul id="nav-mobile" class="left hide-on-med-and-down">
      {% if user.is_authenticated %}
        <li>Welcome {{user.username}}</li>
        <li><a href="/logout">LOGOUT</a></li>
      {% else %}
        <li><a href="/register">REGISTER</a></li>
        <li><a href="/login">LOGIN</a></li>
      {% endif %}
    </ul>
  </div>
</nav>

main/templates/main/includes/navbar2.html
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">DIARYGENIE</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="{% url 'main:homepage' %}">HOME</a></li>
        <li><a href="/register">REGISTER</a></li>
        <li><a href="/login">LOGIN</a></li>
      </ul>
    </div>
</nav>

main/templates/main/login.html
{% extends "main/header.html" %}

{% block content %}
  <div class="row mt-5">
    <div class="col-md-6 m-auto">
      <div class="card card-body text-black bg-white">
        <h1 class="text-center  mb-3"><i class="fas fa-sign-in-alt"></i>  Login</h1>
        <form method="POST">
          {% csrf_token %}
          {{form.as_p}}
      
          <button class="btn" style="background-color:yellow; color:blue"type="submit">Login</button>
        </form>
        <p class="lead mt-4">
          No Account? <a href="{% url 'main:register' %}">Register</a>
        </p>
      </div>
    </div>
  </div>
{% endblock %}

main/templates/main/post_detail.html
{% extends 'main/userpage.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        <h4>{{post.writer}}</h4>
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
        <a class="btn btn-default" href="{% url 'main:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil">Edit</span></a>
        <a class="btn btn-default" href="{% url 'main:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove">Delete</span></a>
    </div>
{% endblock %}

main/templates/main/pub_entry.html
{% extends "main/userpage.html" %}

{% block content %}
  <h1>hi {{user.username}} </h1>
   <div class="row">
    {% for post in posts %}
     <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
      <div class="card-header">published: {{ post.published_date }}</div>
      <div class="card-body">
        <h5 class="card-title"><a href="{% url 'main:post_detail' pk=post.pk %}">{{ post.title }}</a></h5>
        <p class="card-text">{{ post.text|linebreaksbr }}.</p>
      </div>
     </div>
    {% empty %}
      <li> No posts here....</li>
    {% endfor %}
   </div>
   
{% endblock %}

main/templates/main/register.html
{% extends "main/header.html" %}

{% block content %}
  <div class="row mt-5">
    <div class="col-md-6 m-auto">
      <div class="card card-body text-black bg-white">
        <h1 class="text-center mb-3">
          <i class="fas fa-user-plus"></i> Register
        </h1>
        <form method="POST">
          {% csrf_token %}
          {{form.as_p}}

          <button class="btn" style="background-color:yellow; color:blue"type="submit">Register</button>
        </form>
        <p class="lead mt-4">
          If you already have account,<a href="{% url 'main:login' %}"><strong>login</strong></a> instead.
        </p>
      </div>
    </div>
  </div>  
{% endblock %}

main/templates/main/results.html
{% extends "main/userpage.html" %}

{% block content %}
  <h1>hi {{user.username}} </h1>
   <div class="row">
    {% for post in posts %}
     <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
      <div class="card-header">published: {{ post.published_date }}</div>
      <div class="card-body">
        <h5 class="card-title"><a href="{% url 'main:post_detail' pk=post.pk %}">{{ post.title }}</a></h5>
        <p class="card-text">{{ post.text|linebreaksbr }}.</p>
      </div>
     </div>
    {% empty %}
      <li> No posts here....</li>
    {% endfor %}
   </div>
   
{% endblock %}

main/templates/main/thisweek.html
{% extends "main/userpage.html" %}

{% block content %}
  <h1>hi {{user.username}} </h1>
   <div class="row">
    {% for post in posts %}
     <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
      <div class="card-header">published: {{ post.published_date }}</div>
      <div class="card-body">
        <h5 class="card-title"><a href="{% url 'main:post_detail' pk=post.pk %}">{{ post.title }}</a></h5>
        <p class="card-text">{{ post.text|linebreaksbr }}.</p>
      </div>
     </div>
    {% empty %}
      <li> No posts here....</li>
    {% endfor %}
   </div>
   
{% endblock %}

main/templates/main/userpage.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

    
        <link rel="stylesheet" href="{% static 'main/css/bootstrap/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/bootstrap/bootstrap-grid.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/bootstrap/bootstrap-reboot.css' %}">

        <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet" >
        <!-- Compiled and minified CSS -->
        <link href="{% static 'main/css/materialize.css' %}" rel="stylesheet" >
       
       
        <!-- Compiled and minified JavaScript 1920 1080 -->
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Oswald:400,700|Roboto&display=swap" rel="stylesheet">
        
        <script src="https://kit.fontawesome.com/3d9e8d3ff6.js" crossorigin="anonymous"></script>
        <link href="https://bootswatch.com/4/sketchy/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'main/fonts/icomoon/style.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css.map' %}">
        <link rel="stylesheet" href="{% static 'main/css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/bootstrap-datepicker.css' %}">
        <link rel="stylesheet" href="{% static 'main/fonts/flaticon/font/flaticon.css' %}">
      
        <link rel="stylesheet" href="{% static 'main/css/aos.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/jquery.fancybox.min.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/jquery-ui.css' %}">
      
      
        <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
        


        <style>
          body{
            background-image: url('{% static "main/images/page.jpg" %}');
            background-size:1300px 1080px;
            background-repeat: no-repeat;
       
          }
        </style>
       </head>
      
       <body>

        {% include "main/includes/navbar.html" %}
        {% include "main/includes/messages.html" %}
        
        {% block content %}
        {% endblock %}
       
       </body>
       
       <script src="{% static 'tinymce/js/prism.js' %}" ></script>
       <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
       <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
       <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
       <script src="{% static 'main/js/main1.js' %}"></script>
       <script src="{% static 'main/js/main.js' %}"></script>
       <script src="{% static 'main/js/bootstrap.min.js' %}"></script>
       
</html>